const QUESTION_BANK_Economics = {
  economy: [
    {
      tag: "📈 ECONOMY",
      q: "India's first Five Year Plan (1951–56) was based on which model?",
      opts: [
        "Harrod-Domar Model",
        "Mahalanobis Model",
        "Rostow Model",
        "Lewis Model",
      ],
      ans: 0,
      exp: "The First Five Year Plan used the Harrod-Domar model focusing on agriculture and rehabilitation post-partition. The Second Plan (1956–61) used P.C. Mahalanobis's model emphasising heavy industries.",
    },
    {
      tag: "📈 ECONOMY",
      q: 'The "Green Revolution" in India was pioneered by:',
      opts: [
        "M.S. Swaminathan",
        "Norman Borlaug",
        "Verghese Kurien",
        "C. Subramaniam",
      ],
      ans: 0,
      exp: 'M.S. Swaminathan is called the "Father of the Green Revolution in India" for introducing high-yielding variety (HYV) seeds in the 1960s. Norman Borlaug won the Nobel Peace Prize for global wheat research.',
    },
    {
      tag: "📈 ECONOMY",
      q: "The NITI Aayog replaced the Planning Commission in which year?",
      opts: ["2013", "2014", "2015", "2016"],
      ans: 2,
      exp: "NITI (National Institution for Transforming India) Aayog was established on January 1, 2015 replacing the Planning Commission, which was set up in 1950. The PM is its ex-officio chairperson.",
    },
    {
      tag: "📈 ECONOMY",
      q: "India's New Economic Policy of 1991 is known by the acronym:",
      opts: ["PPP", "LPG", "SEZ", "FDI"],
      ans: 1,
      exp: "The 1991 reforms introduced under PM P.V. Narasimha Rao and FM Manmohan Singh are called LPG reforms — Liberalisation, Privatisation and Globalisation — triggered by a balance of payments crisis.",
    },
    {
      tag: "📈 ECONOMY",
      q: "Which committee recommended the introduction of GST in India?",
      opts: [
        "Kelkar Committee",
        "Vijay Kelkar Committee",
        "Asim Dasgupta Committee",
        "Subramanian Committee",
      ],
      ans: 2,
      exp: "The Empowered Committee of State Finance Ministers, chaired by Asim Dasgupta (West Bengal FM), designed the GST framework. The Kelkar Task Force (2002) first proposed GST for India.",
    },
    {
      tag: "📈 ECONOMY",
      q: 'The "White Revolution" or Operation Flood in India is associated with:',
      opts: [
        "M.S. Swaminathan",
        "Sam Pitroda",
        "Verghese Kurien",
        "C.D. Deshmukh",
      ],
      ans: 2,
      exp: 'Verghese Kurien (the "Milkman of India") launched Operation Flood in 1970, making India the world\'s largest milk producer through the cooperative model pioneered by Amul in Gujarat.',
    },
    {
      tag: "📈 ECONOMY",
      q: "The Statutory Liquidity Ratio (SLR) is maintained by commercial banks with:",
      opts: [
        "Central Government",
        "RBI",
        "Themselves (in liquid assets)",
        "SEBI",
      ],
      ans: 2,
      exp: "SLR is the minimum percentage of deposits that banks must maintain themselves in liquid assets (gold, govt securities, cash). CRR is the portion deposited with the RBI.",
    },
    {
      tag: "📈 ECONOMY",
      q: "India's GDP is measured at what base year currently?",
      opts: ["2004-05", "2010-11", "2011-12", "2017-18"],
      ans: 2,
      exp: "India currently uses 2011-12 as the base year for GDP calculation (rebased from 2004-05 in 2015). The methodology uses Gross Value Added (GVA) at basic prices plus net taxes.",
    },
    {
      tag: "📈 ECONOMY",
      q: "MNREGA guarantees employment for how many days per year per rural household?",
      opts: ["90 days", "100 days", "120 days", "150 days"],
      ans: 1,
      exp: "The Mahatma Gandhi National Rural Employment Guarantee Act (2005) guarantees 100 days of unskilled manual work per year per rural household. The wage rate varies by state.",
    },
    {
      tag: "📈 ECONOMY",
      q: 'The "Gini Coefficient" measures:',
      opts: [
        "Economic growth rate",
        "Income/wealth inequality",
        "Human development",
        "Inflation rate",
      ],
      ans: 1,
      exp: "The Gini Coefficient (0 to 1) measures income or wealth inequality. 0 = perfect equality, 1 = perfect inequality. India's Gini coefficient is around 0.35 (moderate inequality).",
    },
    {
      tag: "📈 ECONOMY",
      q: "Which index is used by the RBI as the key inflation measure for monetary policy?",
      opts: [
        "WPI",
        "CPI (Combined)",
        "CPI (Industrial Workers)",
        "GDP deflator",
      ],
      ans: 1,
      exp: "Since 2016, the RBI uses CPI (Consumer Price Index — Combined) as the key inflation target under the flexible inflation targeting framework. The current target is 4% ± 2%.",
    },
    {
      tag: "📈 ECONOMY",
      q: 'The "Laffer Curve" demonstrates the relationship between:',
      opts: [
        "Inflation and unemployment",
        "Tax rates and tax revenue",
        "Savings and investment",
        "GDP growth and debt",
      ],
      ans: 1,
      exp: 'The Laffer Curve shows that tax revenue peaks at an optimal tax rate — too high or too low rates yield less revenue. It was used to justify Reagan\'s "supply-side" tax cuts in the 1980s.',
    },
    {
      tag: "📈 ECONOMY",
      q: "The Pradhan Mantri Jan Dhan Yojana primarily aims at:",
      opts: [
        "Providing crop insurance",
        "Financial inclusion for unbanked citizens",
        "Housing for rural poor",
        "Digital payments",
      ],
      ans: 1,
      exp: "PMJDY (launched Aug 28, 2014) aims at universal financial inclusion — providing a bank account, RuPay debit card, life and accident insurance, and overdraft facility to every Indian.",
    },
    {
      tag: "📈 ECONOMY",
      q: "Which Five Year Plan recorded India's highest average GDP growth rate?",
      opts: ["9th Plan", "10th Plan", "11th Plan", "12th Plan"],
      ans: 2,
      exp: 'The 11th Five Year Plan (2007–12) achieved ~7.9% average GDP growth — the highest ever — under the theme "Faster and More Inclusive Growth." It was chaired by PM Manmohan Singh.',
    },
    {
      tag: "📈 ECONOMY",
      q: 'The "Phillips Curve" shows the relationship between:',
      opts: [
        "Savings and investment",
        "Inflation and unemployment",
        "Money supply and prices",
        "Exchange rate and trade",
      ],
      ans: 1,
      exp: "The Phillips Curve (A.W. Phillips, 1958) shows an inverse relationship between inflation and unemployment — lower unemployment tends to accompany higher inflation, and vice versa.",
    },
    {
      tag: "📈 ECONOMY",
      q: "India's first national budget was presented by:",
      opts: [
        "R.K. Shanmukham Chetty",
        "John Mathai",
        "Jawaharlal Nehru",
        "C.D. Deshmukh",
      ],
      ans: 0,
      exp: "R.K. Shanmukham Chetty presented India's first budget on November 26, 1947 for the period 1947-48. It was a surplus budget of ₹197.4 crore.",
    },
    {
      tag: "📈 ECONOMY",
      q: 'The term "Crowding Out Effect" in economics refers to:',
      opts: [
        "Population pressure on resources",
        "Government borrowing reducing private investment",
        "Urban migration reducing rural workforce",
        "Inflation reducing consumer purchasing power",
      ],
      ans: 1,
      exp: "Crowding Out occurs when government borrowing raises interest rates, reducing funds available for private investment. It is a key argument against excessive deficit financing.",
    },
    {
      tag: "📈 ECONOMY",
      q: "SEBI was established in which year?",
      opts: ["1988", "1990", "1992", "1994"],
      ans: 0,
      exp: "SEBI (Securities and Exchange Board of India) was established in 1988 as a non-statutory body, and given statutory powers by the SEBI Act, 1992 following the Harshad Mehta scam.",
    },
    {
      tag: "📈 ECONOMY",
      q: 'The "Human Development Index" is published annually by:',
      opts: ["World Bank", "IMF", "UNDP", "WHO"],
      ans: 2,
      exp: "The HDI is published in the annual Human Development Report by the UNDP (United Nations Development Programme). It measures three dimensions: health (life expectancy), education and income.",
    },
    {
      tag: "📈 ECONOMY",
      q: "Fiscal deficit is calculated as:",
      opts: [
        "Revenue – Expenditure",
        "Total Expenditure – Revenue Receipts",
        "Total Expenditure – Total Receipts (excluding borrowings)",
        "Capital Expenditure – Capital Receipts",
      ],
      ans: 2,
      exp: "Fiscal Deficit = Total Expenditure – Total Receipts (excluding borrowings/loans). It represents the total borrowing requirement of the government. A higher fiscal deficit means more borrowing and debt.",
    },
  ],
};

