const QUESTION_BANK_Polity = {
  polity: [
    {
      tag: "📜 POLITY",
      q: "Which article of the Indian Constitution abolishes untouchability?",
      opts: ["Article 14", "Article 17", "Article 21", "Article 32"],
      ans: 1,
      exp: "Article 17 abolishes untouchability in any form. Practising it is punishable under the Protection of Civil Rights Act, 1955.",
    },
    {
      tag: "📜 POLITY",
      q: "The Preamble of the Indian Constitution was amended by which constitutional amendment?",
      opts: [
        "42nd Amendment",
        "44th Amendment",
        "52nd Amendment",
        "61st Amendment",
      ],
      ans: 0,
      exp: 'The 42nd Amendment (1976) inserted the words "Socialist", "Secular" and "Integrity" into the Preamble during the Emergency.',
    },
    {
      tag: "📜 POLITY",
      q: "Which Schedule of the Constitution contains the Oath of Office for the President?",
      opts: [
        "Second Schedule",
        "Third Schedule",
        "Fourth Schedule",
        "Fifth Schedule",
      ],
      ans: 1,
      exp: "The Third Schedule contains oaths and affirmations for constitutional functionaries including the President, Vice-President, Ministers and judges.",
    },
    {
      tag: "📜 POLITY",
      q: 'The concept of "Basic Structure" of the Constitution was established in which landmark case?',
      opts: [
        "Golaknath Case",
        "Kesavananda Bharati Case",
        "Minerva Mills Case",
        "Maneka Gandhi Case",
      ],
      ans: 1,
      exp: 'The Kesavananda Bharati v. State of Kerala (1973) ruling by a 13-judge bench established that Parliament cannot amend the "Basic Structure" of the Constitution.',
    },
    {
      tag: "📜 POLITY",
      q: "Which article gives the President the power to proclaim a National Emergency?",
      opts: ["Article 352", "Article 356", "Article 360", "Article 370"],
      ans: 0,
      exp: 'Article 352 empowers the President to proclaim National Emergency on grounds of war, external aggression or armed rebellion (earlier "internal disturbance").',
    },
    {
      tag: "📜 POLITY",
      q: "The Directive Principles of State Policy are borrowed from the Constitution of which country?",
      opts: ["USA", "UK", "Ireland", "Canada"],
      ans: 2,
      exp: "The Directive Principles (Part IV) are borrowed from the Irish Constitution of 1937, which itself was influenced by the Spanish Constitution.",
    },
    {
      tag: "📜 POLITY",
      q: "Which article provides for the formation of new states and alteration of boundaries?",
      opts: ["Article 1", "Article 2", "Article 3", "Article 4"],
      ans: 2,
      exp: "Article 3 empowers Parliament to form new states, increase/decrease the area of existing states, and change their names — by a simple majority.",
    },
    {
      tag: "📜 POLITY",
      q: "The Comptroller and Auditor General of India is appointed by whom?",
      opts: ["Prime Minister", "President", "Parliament", "Finance Minister"],
      ans: 1,
      exp: "The CAG is appointed by the President under Article 148. The CAG audits accounts of the Union and State governments and reports to Parliament.",
    },
    {
      tag: "📜 POLITY",
      q: "Which constitutional article deals with the Right to Constitutional Remedies?",
      opts: ["Article 19", "Article 21", "Article 32", "Article 226"],
      ans: 2,
      exp: 'Article 32 — called the "Heart and Soul" of the Constitution by Dr Ambedkar — guarantees the right to move the Supreme Court for enforcement of Fundamental Rights.',
    },
    {
      tag: "📜 POLITY",
      q: "The Rajya Sabha is a permanent body. How many members retire every two years?",
      opts: ["One-fourth", "One-third", "One-half", "All members"],
      ans: 1,
      exp: 'One-third of Rajya Sabha members retire every two years. Each member serves a 6-year term, making Rajya Sabha a "continuous house" unlike Lok Sabha.',
    },
    {
      tag: "📜 POLITY",
      q: "Which writ is issued to a lower court ordering it to transfer a case to a higher court?",
      opts: ["Habeas Corpus", "Mandamus", "Certiorari", "Quo Warranto"],
      ans: 2,
      exp: 'Certiorari ("to be certified") is issued by a higher court to quash or transfer the order of a lower court or tribunal acting without jurisdiction or in excess of it.',
    },
    {
      tag: "📜 POLITY",
      q: "The Finance Commission is constituted by the President under which article?",
      opts: ["Article 270", "Article 275", "Article 280", "Article 282"],
      ans: 2,
      exp: "Article 280 mandates the President to constitute a Finance Commission every 5 years to recommend distribution of tax revenues between Union and States.",
    },
    {
      tag: "📜 POLITY",
      q: "Zero Hour in Parliament begins at what time?",
      opts: ["11:00 AM", "12:00 Noon", "2:00 PM", "3:00 PM"],
      ans: 1,
      exp: "Zero Hour begins immediately after Question Hour, at 12 noon. Members raise matters of urgent public importance without prior notice during this period.",
    },
    {
      tag: "📜 POLITY",
      q: "Which Schedule of the Constitution deals with anti-defection laws?",
      opts: [
        "Eighth Schedule",
        "Ninth Schedule",
        "Tenth Schedule",
        "Eleventh Schedule",
      ],
      ans: 2,
      exp: "The Tenth Schedule (added by 52nd Amendment, 1985) contains the anti-defection provisions. A member is disqualified if they voluntarily give up party membership or defy party whip.",
    },
    {
      tag: "📜 POLITY",
      q: 'The concept of "judicial review" in India is drawn from the Constitution of which country?',
      opts: ["UK", "USA", "Australia", "France"],
      ans: 1,
      exp: "Judicial Review — the power of courts to examine the constitutionality of laws — is derived from the USA. However, India's version is more limited in scope.",
    },
    {
      tag: "📜 POLITY",
      q: "Who among the following is NOT a member of the National Development Council?",
      opts: [
        "Prime Minister",
        "Chief Ministers of all States",
        "CAG of India",
        "Members of Planning Commission/NITI Aayog",
      ],
      ans: 2,
      exp: "The NDC comprises the PM, Union Cabinet Ministers, Chief Ministers of all States/UTs, and NITI Aayog members. The CAG is not a member.",
    },
    {
      tag: "📜 POLITY",
      q: "Which article of the Constitution deals with equality before law?",
      opts: ["Article 13", "Article 14", "Article 15", "Article 16"],
      ans: 1,
      exp: 'Article 14 states: "The State shall not deny to any person equality before the law or the equal protection of the laws." It combines two concepts from UK and US constitutions.',
    },
    {
      tag: "📜 POLITY",
      q: 'The "Doctrine of Pleasure" in India means the President can remove whom at will?',
      opts: [
        "Governors",
        "Chief Election Commissioner",
        "CAG",
        "Supreme Court judges",
      ],
      ans: 0,
      exp: 'Governors hold office during the "Pleasure of the President" (Article 156), meaning they can be removed without cause. Other constitutional functionaries have security of tenure.',
    },
    {
      tag: "📜 POLITY",
      q: "Which article of the Constitution provides for special provisions for linguistic minorities?",
      opts: ["Article 29", "Article 30", "Article 347", "Article 350A"],
      ans: 3,
      exp: "Article 350A directs every State and local authority to provide adequate facilities for instruction in the mother tongue at the primary stage to children of linguistic minorities.",
    },
    {
      tag: "📜 POLITY",
      q: "The minimum age for a person to become the Vice-President of India is:",
      opts: ["25 years", "30 years", "35 years", "40 years"],
      ans: 2,
      exp: "The minimum age is 35 years (same as the President). The VP must also be a citizen of India and qualified to be elected a Rajya Sabha member.",
    },
  ],
};

