const QUESTION_BANK_Science = {
  science: [
    {
      tag: "🔬 SCIENCE",
      q: "Chandrayaan-3 made India the first country to land near which lunar region?",
      opts: ["Equator", "North Pole", "South Pole", "Far Side"],
      ans: 2,
      exp: "Chandrayaan-3's Vikram lander touched down near the lunar South Pole (~69°S) on August 23, 2023. India became the 4th country to achieve a lunar soft landing and the 1st near the South Pole.",
    },
    {
      tag: "🔬 SCIENCE",
      q: 'Which gas is the primary cause of the "Greenhouse Effect"?',
      opts: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"],
      ans: 2,
      exp: "CO₂ (Carbon Dioxide) is the primary driver of the enhanced greenhouse effect, contributing ~65% of global warming. Others include methane (CH₄), nitrous oxide (N₂O) and water vapour.",
    },
    {
      tag: "🔬 SCIENCE",
      q: "ISRO's first satellite, Aryabhata, was launched in which year?",
      opts: ["1969", "1972", "1975", "1980"],
      ans: 2,
      exp: "Aryabhata, India's first satellite (named after the ancient mathematician), was launched on April 19, 1975 by a Soviet rocket from Kapustin Yar. It was built entirely in India.",
    },
    {
      tag: "🔬 SCIENCE",
      q: 'Which organelle is called the "Powerhouse of the Cell"?',
      opts: ["Nucleus", "Ribosome", "Mitochondria", "Golgi Apparatus"],
      ans: 2,
      exp: "Mitochondria produce ATP (adenosine triphosphate) — the cell's energy currency — through aerobic respiration. They have their own DNA, suggesting they were once independent bacteria.",
    },
    {
      tag: "🔬 SCIENCE",
      q: 'The "Ozone Layer" that protects Earth from UV radiation is found in the:',
      opts: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"],
      ans: 1,
      exp: 'The ozone layer is concentrated in the stratosphere (15–35 km altitude). Chlorofluorocarbons (CFCs) deplete ozone, leading to "holes" especially over Antarctica. The Montreal Protocol (1987) phases out CFCs.',
    },
    {
      tag: "🔬 SCIENCE",
      q: "What is the speed of light in vacuum?",
      opts: ["3 × 10⁶ m/s", "3 × 10⁸ m/s", "3 × 10¹⁰ m/s", "3 × 10¹² m/s"],
      ans: 1,
      exp: "The speed of light in vacuum (c) = 2.998 × 10⁸ m/s ≈ 3 lakh km/s. Einstein's special relativity shows that nothing with mass can reach this speed, and that c is constant in all reference frames.",
    },
    {
      tag: "🔬 SCIENCE",
      q: "Which Article of the Indian Constitution deals with the protection of the environment?",
      opts: ["Article 47", "Article 48A", "Article 51A", "Both 48A and 51A"],
      ans: 3,
      exp: "Article 48A (DPSP) directs the state to protect the environment. Article 51A(g) (Fundamental Duty) obliges citizens to protect the natural environment. Together they form the constitutional basis for environmental law.",
    },
    {
      tag: "🔬 SCIENCE",
      q: 'The "Paris Agreement" on climate change aims to limit global warming to:',
      opts: [
        "1°C above pre-industrial levels",
        "1.5–2°C above pre-industrial levels",
        "2.5–3°C above pre-industrial levels",
        "3°C above pre-industrial levels",
      ],
      ans: 1,
      exp: "The Paris Agreement (COP21, 2015) aims to limit global temperature rise to well below 2°C above pre-industrial levels, with efforts to limit it to 1.5°C. India ratified it in October 2016.",
    },
    {
      tag: "🔬 SCIENCE",
      q: 'India\'s MOM (Mars Orbiter Mission) "Mangalyaan" was launched in:',
      opts: ["2012", "2013", "2014", "2015"],
      ans: 1,
      exp: "Mangalyaan was launched on November 5, 2013 and entered Mars orbit on September 24, 2014. India became the first country to succeed in its first Mars attempt and at the lowest cost ($74 million).",
    },
    {
      tag: "🔬 SCIENCE",
      q: "DNA double helix structure was discovered by:",
      opts: [
        "Louis Pasteur and Robert Koch",
        "Watson and Crick",
        "Mendel and Darwin",
        "Franklin and Wilkins",
      ],
      ans: 1,
      exp: "Watson and Crick published the double helix structure of DNA in 1953, using Rosalind Franklin's X-ray crystallography data (Photo 51). They shared the 1962 Nobel Prize with Maurice Wilkins.",
    },
    {
      tag: "🔬 SCIENCE",
      q: 'The phenomenon of "acid rain" is primarily caused by:',
      opts: [
        "CO₂ and Methane",
        "SO₂ and NOₓ",
        "Ozone and Chlorine",
        "Dust and Smoke",
      ],
      ans: 1,
      exp: "Acid rain is caused when SO₂ (sulphur dioxide) and NOₓ (nitrogen oxides) from burning fossil fuels react with water vapour to form sulphuric and nitric acids, with pH below 5.6.",
    },
    {
      tag: "🔬 SCIENCE",
      q: 'Which Indian scientist discovered the "Raman Effect"?',
      opts: [
        "Homi Bhabha",
        "Jagadish Chandra Bose",
        "C.V. Raman",
        "Srinivasa Ramanujan",
      ],
      ans: 2,
      exp: "C.V. Raman discovered the Raman Effect (inelastic scattering of light) on February 28, 1928 — now celebrated as National Science Day. He won the 1930 Nobel Prize in Physics, the first Asian to do so.",
    },
    {
      tag: "🔬 SCIENCE",
      q: 'The "Convention on Biological Diversity" (CBD) was signed at:',
      opts: [
        "Stockholm, 1972",
        "Rio de Janeiro, 1992",
        "Kyoto, 1997",
        "Johannesburg, 2002",
      ],
      ans: 1,
      exp: "The CBD was signed at the Earth Summit (Rio de Janeiro, 1992) and came into force in 1993. It has three objectives: conservation of biodiversity, sustainable use, and equitable sharing of genetic resources.",
    },
    {
      tag: "🔬 SCIENCE",
      q: "Which is the most abundant gas in the Earth's atmosphere?",
      opts: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
      ans: 2,
      exp: "Nitrogen (N₂) makes up ~78% of Earth's atmosphere, followed by Oxygen (21%), Argon (0.93%) and CO₂ (0.04%). Nitrogen is essential for proteins and nucleic acids in all living organisms.",
    },
    {
      tag: "🔬 SCIENCE",
      q: "Biosphere Reserves in India are designated by:",
      opts: [
        "IUCN",
        "UNESCO",
        "Ministry of Environment, Forest and Climate Change",
        "Wildlife Institute of India",
      ],
      ans: 2,
      exp: "Biosphere Reserves in India are designated by the Ministry of Environment. India has 18 Biosphere Reserves; 12 are included in UNESCO's World Network of Biosphere Reserves.",
    },
    {
      tag: "🔬 SCIENCE",
      q: "Malaria is caused by which type of microorganism?",
      opts: ["Bacteria", "Virus", "Protozoa", "Fungi"],
      ans: 2,
      exp: "Malaria is caused by Plasmodium protozoa (P. falciparum, P. vivax etc.) transmitted by the female Anopheles mosquito. Ronald Ross won the 1902 Nobel Prize for proving mosquito transmission.",
    },
    {
      tag: "🔬 SCIENCE",
      q: "India's first indigenously developed nuclear reactor is:",
      opts: ["Apsara", "Dhruva", "Kamini", "Purnima"],
      ans: 0,
      exp: "Apsara, commissioned in August 1956 at BARC Trombay, was India's first nuclear reactor and Asia's first. It was designed entirely by Indian scientists under Homi Bhabha.",
    },
    {
      tag: "🔬 SCIENCE",
      q: 'The "Blue Carbon" ecosystems that store large amounts of carbon include:',
      opts: [
        "Tropical rainforests",
        "Mangroves, seagrasses and tidal marshes",
        "Boreal forests",
        "Arctic tundra",
      ],
      ans: 1,
      exp: "Blue Carbon refers to carbon stored in coastal and marine ecosystems — mangroves, seagrasses and salt marshes. They sequester carbon up to 5x faster than tropical forests per unit area.",
    },
    {
      tag: "🔬 SCIENCE",
      q: "The SI unit of radioactivity is:",
      opts: ["Curie", "Becquerel", "Roentgen", "Sievert"],
      ans: 1,
      exp: "The Becquerel (Bq) = 1 nuclear decay per second, named after Henri Becquerel who discovered radioactivity in 1896. The older unit Curie = 3.7 × 10¹⁰ Bq (activity of 1g of radium).",
    },
    {
      tag: "🔬 SCIENCE",
      q: "Project Tiger was launched in India in which year?",
      opts: ["1967", "1970", "1973", "1980"],
      ans: 2,
      exp: "Project Tiger was launched by PM Indira Gandhi on April 1, 1973 at Jim Corbett National Park. Tiger population was then ~1,800; by 2023 India had ~3,682 tigers — over 75% of the world's wild tigers.",
    },
  ],
};

