const QUESTION_BANK_History = {
  history: [
    {
      tag: "🏛️ HISTORY",
      q: "Who founded the Maurya Empire?",
      opts: ["Ashoka", "Bindusara", "Chandragupta Maurya", "Samudragupta"],
      ans: 2,
      exp: "Chandragupta Maurya (321 BCE) founded the Maurya Empire with guidance from Chanakya (Kautilya). He defeated the Nanda dynasty and united much of the Indian subcontinent.",
    },
    {
      tag: "🏛️ HISTORY",
      q: "The Battle of Plassey (1757) was fought between the British and:",
      opts: [
        "Hyder Ali",
        "Siraj-ud-Daulah",
        "Tipu Sultan",
        "Nizam of Hyderabad",
      ],
      ans: 1,
      exp: "The Battle of Plassey was fought between Robert Clive's British forces and Siraj-ud-Daulah, the Nawab of Bengal. Mir Jafar's betrayal sealed the outcome, giving Britain control over Bengal.",
    },
    {
      tag: "🏛️ HISTORY",
      q: "Which ancient university was the world's first residential university, attracting students from across Asia?",
      opts: ["Takshashila", "Nalanda", "Vikramashila", "Valabhi"],
      ans: 1,
      exp: "Nalanda University (5th–12th century CE) in Bihar was the world's first great residential university, with 10,000+ students from China, Korea, Japan and Southeast Asia.",
    },
    {
      tag: "🏛️ HISTORY",
      q: "The Dandi March (1930) was a protest against:",
      opts: [
        "Partition of Bengal",
        "Salt Tax",
        "Rowlatt Act",
        "Simon Commission",
      ],
      ans: 1,
      exp: "Gandhi led the 241-mile Dandi March (Mar 12 – Apr 5, 1930) to protest the British salt monopoly and salt tax. It launched the Civil Disobedience Movement.",
    },
    {
      tag: "🏛️ HISTORY",
      q: "Who was the first Governor-General of independent India?",
      opts: [
        "Lord Mountbatten",
        "C. Rajagopalachari",
        "Dr. Rajendra Prasad",
        "Sardar Patel",
      ],
      ans: 0,
      exp: "Lord Mountbatten was the first Governor-General of independent India (Aug 1947 – Jun 1948). C. Rajagopalachari succeeded him as the last and only Indian Governor-General (1948–50).",
    },
    {
      tag: "🏛️ HISTORY",
      q: "The Indus Valley Civilization was primarily discovered at which two sites first?",
      opts: [
        "Mohenjo-daro and Lothal",
        "Harappa and Mohenjo-daro",
        "Kalibangan and Dholavira",
        "Rakhigarhi and Harappa",
      ],
      ans: 1,
      exp: "Harappa (discovered 1921 by Daya Ram Sahni) and Mohenjo-daro (1922 by R.D. Banerji) were the first major Indus Valley sites excavated, revealing a sophisticated Bronze Age civilisation.",
    },
    {
      tag: "🏛️ HISTORY",
      q: 'Akbar\'s policy of "Sulh-i-kul" means:',
      opts: [
        "Universal Brotherhood",
        "Absolute Peace",
        "Peace with All",
        "Divine Faith",
      ],
      ans: 2,
      exp: '"Sulh-i-kul" (Persian: Peace with All) was Akbar\'s policy of universal religious tolerance. It formed the basis of his Din-i-Ilahi religious movement and his inclusive governance.',
    },
    {
      tag: "🏛️ HISTORY",
      q: "The Partition of Bengal (1905) was carried out by which Viceroy?",
      opts: ["Lord Curzon", "Lord Minto", "Lord Hardinge", "Lord Ripon"],
      ans: 0,
      exp: 'Lord Curzon partitioned Bengal in October 1905, ostensibly for administrative efficiency but seen as a "divide and rule" strategy. It sparked the Swadeshi Movement and was annulled in 1911.',
    },
    {
      tag: "🏛️ HISTORY",
      q: 'Who gave the title "Mahatma" to Mohandas Gandhi?',
      opts: [
        "Jawaharlal Nehru",
        "Bal Gangadhar Tilak",
        "Rabindranath Tagore",
        "Gopal Krishna Gokhale",
      ],
      ans: 2,
      exp: 'Rabindranath Tagore first referred to Gandhi as "Mahatma" (Great Soul) in 1915. Gandhi himself was uncomfortable with the title and preferred being called "Bapu" (Father).',
    },
    {
      tag: "🏛️ HISTORY",
      q: "The Doctrine of Lapse was used by which British Governor-General to annex Indian states?",
      opts: [
        "Lord Wellesley",
        "Lord Dalhousie",
        "Lord Cornwallis",
        "Lord Hastings",
      ],
      ans: 1,
      exp: "Lord Dalhousie (1848–56) used the Doctrine of Lapse to annex states without a natural heir, including Satara, Jhansi, Nagpur and Awadh — a major cause of the 1857 Revolt.",
    },
    {
      tag: "🏛️ HISTORY",
      q: "The Chauri Chaura incident (1922) led to the withdrawal of which movement?",
      opts: [
        "Swadeshi Movement",
        "Home Rule Movement",
        "Non-Cooperation Movement",
        "Civil Disobedience Movement",
      ],
      ans: 2,
      exp: "When a mob at Chauri Chaura (UP) burned a police station killing 22 policemen, Gandhi suspended the Non-Cooperation Movement, believing the masses were not ready for non-violent resistance.",
    },
    {
      tag: "🏛️ HISTORY",
      q: "The Sangam Age refers to the literary period in ancient:",
      opts: ["North India", "Eastern India", "Tamil Nadu", "Karnataka"],
      ans: 2,
      exp: 'The Sangam Age (300 BCE – 300 CE) refers to the classical period of Tamil literature produced during three "Sangams" (literary academies) in ancient Tamil Nadu.',
    },
    {
      tag: "🏛️ HISTORY",
      q: "Who established the Asiatic Society of Bengal in 1784?",
      opts: [
        "Warren Hastings",
        "William Jones",
        "James Prinsep",
        "Charles Wilkins",
      ],
      ans: 1,
      exp: "Sir William Jones founded the Asiatic Society of Bengal in Calcutta (1784) to study the history, antiquities, arts and sciences of Asia. He was the first to suggest Sanskrit's relationship to European languages.",
    },
    {
      tag: "🏛️ HISTORY",
      q: 'The famous "Quit India" speech by Gandhi was delivered at:',
      opts: ["Sabarmati Ashram", "Gowalia Tank, Bombay", "Wardha", "Lucknow"],
      ans: 1,
      exp: 'Gandhi delivered the "Do or Die" / Quit India speech at Gowalia Tank Maidan, Bombay on August 8, 1942, launching the Quit India Movement. He was arrested the very next morning.',
    },
    {
      tag: "🏛️ HISTORY",
      q: "The Permanent Settlement of 1793 was introduced in Bengal by:",
      opts: ["Lord Clive", "Lord Cornwallis", "Lord Wellesley", "Lord Ripon"],
      ans: 1,
      exp: "Lord Cornwallis introduced the Permanent Settlement (Zamindari System) in 1793, fixing the land revenue permanently with zamindars. It made zamindars the owners of land but impoverished peasants.",
    },
    {
      tag: "🏛️ HISTORY",
      q: "Which Mughal Emperor built the Taj Mahal?",
      opts: ["Akbar", "Jahangir", "Shah Jahan", "Aurangzeb"],
      ans: 2,
      exp: "Shah Jahan built the Taj Mahal (1632–53) in Agra as a mausoleum for his wife Mumtaz Mahal. It was designed by Ustad Ahmad Lahauri and is a UNESCO World Heritage Site.",
    },
    {
      tag: "🏛️ HISTORY",
      q: "The INC was founded in 1885 by:",
      opts: [
        "Dadabhai Naoroji",
        "A.O. Hume",
        "W.C. Bonnerjee",
        "Bal Gangadhar Tilak",
      ],
      ans: 1,
      exp: "Allan Octavian Hume, a retired British civil servant, founded the Indian National Congress in 1885. The first session was held in Bombay with W.C. Bonnerjee as the first president.",
    },
    {
      tag: "🏛️ HISTORY",
      q: 'In which year did India conduct its first nuclear test "Smiling Buddha"?',
      opts: ["1962", "1968", "1974", "1998"],
      ans: 2,
      exp: 'India\'s first nuclear test, codenamed "Smiling Buddha," was conducted on May 18, 1974 at Pokhran, Rajasthan under PM Indira Gandhi. The second test "Pokhran-II" was in 1998.',
    },
    {
      tag: "🏛️ HISTORY",
      q: 'The famous "Third Battle of Panipat" (1761) was fought between:',
      opts: [
        "Marathas and Mughals",
        "Marathas and Afghans",
        "Marathas and British",
        "Sikhs and Afghans",
      ],
      ans: 1,
      exp: "The Third Battle of Panipat (Jan 14, 1761) was fought between the Marathas (under Vishwasrao, Bhau Saheb) and the Afghans (Ahmad Shah Durrani). The decisive Afghan victory ended Maratha dominance.",
    },
    {
      tag: "🏛️ HISTORY",
      q: "The Rowlatt Act (1919) was opposed because it allowed:",
      opts: [
        "Deportation without trial",
        "Detention without trial",
        "Execution without trial",
        "Taxation without representation",
      ],
      ans: 1,
      exp: "The Rowlatt Act (Black Act) allowed indefinite detention without trial for suspected revolutionaries. Gandhi called for a hartal (strike) against it, which led to the Jallianwala Bagh massacre.",
    },
  ],
};

